import { serializeLocalDateTime } from './appointment-utils.js'
import { getSession } from './api.js'

document.body.classList.add('appointment-confirmation-shell')
document.querySelector('.app-shell')?.classList.add('appointment-confirmation-shell')

const form = document.getElementById('booking-form'), specialty = document.getElementById('specialty'), doctor = document.getElementById('doctor'), dateInput = document.getElementById('appointment-date'), reason = document.getElementById('reason'), slots = document.getElementById('slots'), error = document.getElementById('booking-error'), submit = document.getElementById('submit-booking'), selection = document.getElementById('booking-selection'), summary = document.getElementById('slot-summary')
const steps = [...document.querySelectorAll('.booking-steps li')]
let patientId = null, doctors = [], selectedSlot = null
function headers() { const session = getSession(), token = session?.jwToken || session?.jwtToken || session?.token; return token ? { Authorization: `Bearer ${token}` } : {} }
async function request(url, options = {}) { const response = await fetch(url, { ...options, headers: { ...headers(), 'Content-Type': 'application/json', ...(options.headers || {}) } }), payload = await response.json().catch(() => null); if (response.status === 401) throw new Error('Tu sesión no es válida o ha expirado.'); if (!response.ok || !payload?.success) throw new Error(payload?.message || 'No se pudo completar la operación.'); return payload.data }
function setError(field, message = '') { document.getElementById(`${field}-error`).textContent = message; document.getElementById(field === 'date' ? 'appointment-date' : field)?.setAttribute('aria-invalid', String(Boolean(message))) }
function clearFeedback() { error.hidden = true; error.textContent = '' }
function showError(message) { error.textContent = message; error.hidden = false; error.scrollIntoView({ behavior: 'smooth', block: 'nearest' }) }
function setCurrentStep(index) { steps.forEach((step, position) => { const completed = position < index, current = position === index; step.classList.toggle('is-complete', completed); step.classList.toggle('is-current', current); if (current) step.setAttribute('aria-current', 'step'); else step.removeAttribute('aria-current') }) }
const formatDate = value => new Intl.DateTimeFormat('es-DO', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(value)
const formatTime = value => new Intl.DateTimeFormat('es-DO', { hour: '2-digit', minute: '2-digit' }).format(value)
const getDay = value => ((new Date(`${value}T00:00:00`).getDay() + 6) % 7) + 1
const toDateTime = (date, time) => new Date(`${date}T${time}`)
function resetSlots(message = 'Selecciona un profesional y una fecha para consultar horarios.') { selectedSlot = null; slots.replaceChildren(); summary.textContent = message; selection.textContent = 'Aún no has seleccionado un horario.'; submit.disabled = true; setError('time') }
function updateDoctors() { const specialtyId = specialty.value; doctor.replaceChildren(new Option(specialtyId ? 'Selecciona un profesional' : 'Selecciona primero una especialidad', '')); doctors.filter(item => item.specialtyId === specialtyId).forEach(item => doctor.add(new Option(`Profesional · Lic. ${item.medicalLicense || 'No disponible'}`, item.id))); doctor.disabled = !specialtyId; dateInput.disabled = true; resetSlots() }
async function loadSlots() { clearFeedback(); setError('date'); resetSlots('Consultando horarios disponibles…'); if (!doctor.value || !dateInput.value) return; try { const [availability, appointments] = await Promise.all([request(`/api/availability/doctor/${encodeURIComponent(doctor.value)}`), request(`/api/appointments/doctor/${encodeURIComponent(doctor.value)}`)]), occupied = new Set(appointments.filter(item => item.status !== 4 && new Date(item.dateTime).toDateString() === toDateTime(dateInput.value, '00:00').toDateString()).map(item => new Date(item.dateTime).getTime())), available = []; availability.filter(item => item.day === getDay(dateInput.value)).forEach(block => { const cursor = toDateTime(dateInput.value, block.startTime), end = toDateTime(dateInput.value, block.endTime); while (cursor < end) { if (cursor > new Date() && !occupied.has(cursor.getTime())) available.push(new Date(cursor)); cursor.setMinutes(cursor.getMinutes() + 30) } }); if (!available.length) { summary.textContent = 'No hay horarios libres en esta fecha.'; slots.innerHTML = '<p class="booking-empty">Prueba con otra fecha o selecciona otro profesional.</p>'; return } summary.textContent = `${available.length} horario${available.length === 1 ? '' : 's'} disponible${available.length === 1 ? '' : 's'} el ${formatDate(toDateTime(dateInput.value, '00:00'))}.`; const grid = document.createElement('div'); grid.className = 'booking-slot-grid'; available.forEach(slot => { const button = document.createElement('button'); button.type = 'button'; button.className = 'booking-slot'; button.textContent = formatTime(slot); button.setAttribute('aria-pressed', 'false'); button.addEventListener('click', () => { selectedSlot = slot; grid.querySelectorAll('button').forEach(item => { item.classList.remove('is-selected'); item.setAttribute('aria-pressed', 'false') }); button.classList.add('is-selected'); button.setAttribute('aria-pressed', 'true'); selection.textContent = `${formatDate(slot)} · ${formatTime(slot)}`; submit.disabled = !reason.value.trim(); setCurrentStep(2); setError('time') }); grid.append(button) }); slots.append(grid) } catch (exception) { resetSlots('No fue posible consultar los horarios.'); showError(exception.message) } }
async function initialize() { dateInput.min = new Date().toISOString().slice(0, 10); try { const [patient, specialtyList, doctorList] = await Promise.all([request('/api/patients/me'), request('/api/specialties'), request('/api/doctors')]); patientId = patient.id; doctors = doctorList; specialty.replaceChildren(new Option('Selecciona una especialidad', '')); specialtyList.forEach(item => specialty.add(new Option(item.name, item.id))); specialty.disabled = false } catch (exception) { showError(exception.message || 'No se pudo preparar el formulario de agendamiento.') } }
const escapeHtml = value => String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character])
const icon = (name) => ({
  success: '<svg viewBox="0 0 48 48" aria-hidden="true"><path d="m14 24 7 7 14-16"/></svg>',
  calendar: '<svg viewBox="0 0 32 32" aria-hidden="true"><rect x="5" y="7" width="22" height="20" rx="2"/><path d="M10 4v6m12-6v6M5 13h22m-12 5v6m-3-3h6"/></svg>',
  stethoscope: '<svg viewBox="0 0 42 42" aria-hidden="true"><path d="M14 6v10a7 7 0 0 0 14 0V6m-14 0h-3m3 0h3m11 0h3m-3 0h-3M21 23v6a6 6 0 0 0 12 0v-3"/><circle cx="33" cy="22" r="3"/></svg>',
  professional: '<svg viewBox="0 0 42 42" aria-hidden="true"><circle cx="21" cy="11" r="6"/><path d="M10 34v-4c0-5 5-9 11-9s11 4 11 9v4"/><path d="M28 23v11m-4-7h8m-8 4h8"/></svg>',
  time: '<svg viewBox="0 0 42 42" aria-hidden="true"><circle cx="21" cy="21" r="14"/><path d="M21 13v9l6 4"/></svg>',
  history: '<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M6 15a10 10 0 1 1 3 7"/><path d="M6 22v-6h6m4-7v7l-4-2"/></svg>',
  appointmentStatus: '<svg viewBox="0 0 24 24" aria-hidden="true"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10"/></svg>'
}[name])
specialty.addEventListener('change', () => { setError('specialty'); updateDoctors(); setCurrentStep(0) }); doctor.addEventListener('change', () => { setError('doctor'); dateInput.disabled = !doctor.value; resetSlots(doctor.value ? 'Selecciona una fecha para consultar horarios.' : undefined); if (doctor.value) setCurrentStep(1) }); dateInput.addEventListener('change', loadSlots); reason.addEventListener('input', () => { document.getElementById('reason-count').textContent = `${reason.value.length}/500`; setError('reason'); submit.disabled = !selectedSlot || !reason.value.trim() })
form.addEventListener('submit', async event => { event.preventDefault(); clearFeedback(); let valid = true; if (!specialty.value) { setError('specialty', 'Selecciona una especialidad.'); valid = false } if (!doctor.value) { setError('doctor', 'Selecciona un profesional.'); valid = false } if (!dateInput.value) { setError('date', 'Selecciona una fecha.'); valid = false } if (!selectedSlot) { setError('time', 'Selecciona un horario disponible.'); valid = false } if (!reason.value.trim()) { setError('reason', 'Describe brevemente el motivo de tu consulta.'); valid = false } if (!valid || !patientId) return; submit.disabled = true; submit.textContent = 'Agendando cita…'; try { await request('/api/appointments', { method: 'POST', body: JSON.stringify({ patientId, doctorId: doctor.value, dateTime: serializeLocalDateTime(selectedSlot), reason: reason.value.trim() }) }); const doctorLabel = escapeHtml(doctor.selectedOptions[0].textContent), specialtyLabel = escapeHtml(specialty.selectedOptions[0].textContent), dateLabel = escapeHtml(formatDate(selectedSlot)), timeLabel = escapeHtml(formatTime(selectedSlot)); document.getElementById('booking-confirmation').innerHTML = `<div class="confirmation-success"><div class="confirmation-burst" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="confirmation-icon">${icon('success')}</div><h2>¡Cita registrada con éxito!</h2><p>Hemos recibido tu solicitud y te notificaremos cuando sea confirmada.</p></div><section class="appointment-details" aria-labelledby="appointment-details-title"><div class="appointment-details-heading"><span></span><h3 id="appointment-details-title">${icon('calendar')}Detalles de tu cita</h3><span></span></div><dl class="appointment-details-card"><div class="appointment-detail"><div class="appointment-detail-icon">${icon('stethoscope')}</div><dt>Especialidad</dt><dd>${specialtyLabel}</dd></div><div class="appointment-detail"><div class="appointment-detail-icon">${icon('professional')}</div><dt>Profesional</dt><dd>${doctorLabel}</dd></div><div class="appointment-detail"><div class="appointment-detail-icon">${icon('time')}</div><dt>Fecha y hora</dt><dd>${dateLabel}</dd><time>${icon('history')}${timeLabel}</time></div></dl></section><a class="appointment-status-link" href="/mis-citas.html">${icon('appointmentStatus')}<span>Ver estado de mi cita</span></a>`; document.getElementById('booking-confirmation').hidden = false; document.querySelector('.booking-page')?.classList.add('is-confirmed'); form.hidden = true; setCurrentStep(2); document.getElementById('booking-confirmation').scrollIntoView({ behavior: 'smooth', block: 'start' }) } catch (exception) { showError(exception.message); submit.disabled = false; submit.textContent = 'Confirmar cita' } })
initialize()
